github:
  description: "Official Dockerfile for Apache Spark"
  homepage: https://spark.apache.org/
  features:
    issues: true
  labels:
    - python
    - scala
    - r
    - java
    - big-data
    - jdbc
    - sql
    - spark
  enabled_merge_buttons:
    merge: false
    squash: true
    rebase: true

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  pullrequests: reviews@spark.apache.org
  issues: reviews@spark.apache.org
  commits: commits@spark.apache.org

